#! /system/bin/sh
if [ $# == 0 ]; then
	port='30333'
else
	port=$1
fi
echo Running lidadbg server at port $port
"$(dirname "${BASH_SOURCE[0]}")"/arm64-v8a/lldb-server platform --server --listen *:$port